version: '3.8'

services:
  app:
    build: .
    image: smart-heat-alert-api:1.0.0
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/heatalert
      SPRING_DATASOURCE_USERNAME: usuario
      SPRING_DATASOURCE_PASSWORD: senha
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRINGDOC_API_DOCS_PATH: /api-docs
      SPRINGDOC_SWAGGER_UI_PATH: /swagger-ui.html
      JAVA_OPTS: "-Xms256m -Xmx512m -Djava.security.egd=file:/dev/./urandom"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s  

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    image: custom-postgres:15-alpine
    environment:
      POSTGRES_DB: heatalert
      POSTGRES_USER: usuario  
      POSTGRES_PASSWORD: senha
      TZ: America/Sao_Paulo
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usuario -d heatalert"]  
      interval: 5s
      timeout: 5s
      retries: 10  
      start_period: 10s

volumes:
  pgdata: